/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ..\sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type GalleryItemImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "galleryItem.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Logo = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type BrandsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "brands.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type BrandShowcase = {
  _type: 'brandShowcase'
  subtitle?: string
  heading?: string
  description?: string
  brands?: Array<{
    name?: string
    logo?: Logo
    image?: BrandsObjectImage
    description?: string
    website?: string
    color?: string
    _key: string
  }>
}

export type ContactSection = {
  _type: 'contactSection'
  subtitle?: string
  heading?: string
  description?: string
  addressHeading?: string
  address?: string
  phoneHeading?: string
  phones?: Array<string>
  emailHeading?: string
  email?: string
}

export type QualityEthics = {
  _type: 'qualityEthics'
  subtitle?: string
  heading?: string
  description?: string
  checklist?: Array<string>
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type QualityStandards = {
  _type: 'qualityStandards'
  subtitle?: string
  heading?: string
  description?: string
  features?: Array<{
    title?: string
    description?: string
    icon?: 'shield' | 'refresh' | 'clipboard'
    _key: string
  }>
}

export type ProductShowcase = {
  _type: 'productShowcase'
  subtitle?: string
  heading?: string
  description?: string
  products?: Array<{
    number?: string
    title?: string
    description?: string
    features?: Array<string>
    image?: ObjectImage
    buttonText?: string
    buttonLink?: string
    _key: string
  }>
}

export type InfrastructureSection = {
  _type: 'infrastructureSection'
  subtitle?: string
  heading?: string
  description?: string
  cards?: Array<{
    icon?: 'design' | 'precision' | 'testing'
    title?: string
    description?: string
    _key: string
  }>
}

export type WorkflowSection = {
  _type: 'workflowSection'
  subtitle?: string
  heading?: string
  description?: string
  steps?: Array<{
    number?: string
    title?: string
    description?: string
    _key: string
  }>
}

export type GallerySection = {
  _type: 'gallerySection'
  subtitle?: string
  heading?: string
  items?: Array<{
    image?: GalleryItemImage
    title?: string
    description?: string
    link?: string
    _type: 'galleryItem'
    _key: string
  }>
}

export type LocationSection = {
  _type: 'locationSection'
  locations?: Array<{
    label?: string
    city?: string
    description?: string
    features?: Array<string>
    _key: string
  }>
}

export type AboutHero = {
  _type: 'aboutHero'
  subtitle?: string
  heading?: string
  description?: string
  quote?: string
  quoteAuthor?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type CtaSection = {
  _type: 'ctaSection'
  heading?: string
  description?: string
  primaryButtonText?: string
  secondaryButtonText?: string
}

export type Services = {
  _type: 'services'
  heading?: string
  subheading?: string
  description?: string
  serviceItems?: Array<{
    title?: string
    description?: string
    icon?: 'PenTool' | 'Factory' | 'ShieldCheck' | 'Truck'
    _key: string
  }>
}

export type ProductCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'productCategory'
}

export type ProductLookbook = {
  _type: 'productLookbook'
  heading?: string
  products?: Array<
    {
      _key: string
    } & ProductCategoryReference
  >
}

export type ProductCategory = {
  _id: string
  _type: 'productCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  features?: Array<string>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Philosophy = {
  _type: 'philosophy'
  heading?: string
  subheading?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  features?: Array<string>
  ctaText?: string
  ctaLink?: string
}

export type Stats = {
  _type: 'stats'
  items?: Array<{
    value?: string
    label?: string
    icon?: 'Globe' | 'Award' | 'Factory' | 'Users' | 'Leaf' | 'ShieldCheck'
    _key: string
  }>
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type Hero = {
  _type: 'hero'
  heading: string
  subheading?: string
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  buttonText?: string
  buttonLink?: string
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & Stats)
    | ({
        _key: string
      } & Philosophy)
    | ({
        _key: string
      } & ProductLookbook)
    | ({
        _key: string
      } & Services)
    | ({
        _key: string
      } & CtaSection)
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & AboutHero)
    | ({
        _key: string
      } & LocationSection)
    | ({
        _key: string
      } & GallerySection)
    | ({
        _key: string
      } & WorkflowSection)
    | ({
        _key: string
      } & InfrastructureSection)
    | ({
        _key: string
      } & ProductShowcase)
    | ({
        _key: string
      } & QualityStandards)
    | ({
        _key: string
      } & QualityEthics)
    | ({
        _key: string
      } & ContactSection)
    | ({
        _key: string
      } & BrandShowcase)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headerMenu?: Array<{
    title?: string
    link?: string
    _key: string
  }>
  footerDescription?: string
  contactEmail?: string
  locations?: Array<{
    city?: string
    address?: string
    _key: string
  }>
  socialLinks?: Array<{
    platform?: string
    url?: string
    _key: string
  }>
  companyProfile?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  copyrightText?: string
  legalLinks?: Array<{
    label?: string
    url?: string
    _key: string
  }>
  certificationsText?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | GalleryItemImage
  | ObjectImage
  | Logo
  | BrandsObjectImage
  | BrandShowcase
  | ContactSection
  | QualityEthics
  | QualityStandards
  | ProductShowcase
  | InfrastructureSection
  | WorkflowSection
  | GallerySection
  | LocationSection
  | AboutHero
  | CtaSection
  | Services
  | ProductCategoryReference
  | ProductLookbook
  | ProductCategory
  | SanityImageCrop
  | SanityImageHotspot
  | Philosophy
  | Stats
  | PageReference
  | PostReference
  | Link
  | Hero
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Page
  | PersonReference
  | Post
  | Person
  | Slug
  | SanityFileAssetReference
  | SiteSettings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity\lib\queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }  }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },      _type == "productLookbook" => {        ...,        products[]->{          _id,          title,          description,          image,          features        }      },      // 👇 ADD YOUR NEW BLOCKS HERE IF NEEDED TO FETCH DATA      _type == "brandShowcase" => { ... },      _type == "contactSection" => { ... },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'aboutHero'
        subtitle?: string
        heading?: string
        description?: string
        quote?: string
        quoteAuthor?: string
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
      }
    | {
        _key: string
        _type: 'brandShowcase'
        subtitle?: string
        heading?: string
        description?: string
        brands?: Array<{
          name?: string
          logo?: Logo
          image?: BrandsObjectImage
          description?: string
          website?: string
          color?: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        button: {
          _type: 'button'
          buttonText?: string
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          } | null
        } | null
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light'
        contentAlignment?: 'imageFirst' | 'textFirst'
      }
    | {
        _key: string
        _type: 'contactSection'
        subtitle?: string
        heading?: string
        description?: string
        addressHeading?: string
        address?: string
        phoneHeading?: string
        phones?: Array<string>
        emailHeading?: string
        email?: string
      }
    | {
        _key: string
        _type: 'ctaSection'
        heading?: string
        description?: string
        primaryButtonText?: string
        secondaryButtonText?: string
      }
    | {
        _key: string
        _type: 'gallerySection'
        subtitle?: string
        heading?: string
        items?: Array<{
          image?: GalleryItemImage
          title?: string
          description?: string
          link?: string
          _type: 'galleryItem'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'hero'
        heading: string
        subheading?: string
        backgroundImage?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
        buttonText?: string
        buttonLink?: string
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        > | null
      }
    | {
        _key: string
        _type: 'infrastructureSection'
        subtitle?: string
        heading?: string
        description?: string
        cards?: Array<{
          icon?: 'design' | 'precision' | 'testing'
          title?: string
          description?: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'locationSection'
        locations?: Array<{
          label?: string
          city?: string
          description?: string
          features?: Array<string>
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'philosophy'
        heading?: string
        subheading?: string
        description?: string
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        }
        features?: Array<string>
        ctaText?: string
        ctaLink?: string
      }
    | {
        _key: string
        _type: 'productLookbook'
        heading?: string
        products: Array<{
          _id: string
          title: string | null
          description: string | null
          image: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          } | null
          features: Array<string> | null
        }> | null
      }
    | {
        _key: string
        _type: 'productShowcase'
        subtitle?: string
        heading?: string
        description?: string
        products?: Array<{
          number?: string
          title?: string
          description?: string
          features?: Array<string>
          image?: ObjectImage
          buttonText?: string
          buttonLink?: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'qualityEthics'
        subtitle?: string
        heading?: string
        description?: string
        checklist?: Array<string>
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
      }
    | {
        _key: string
        _type: 'qualityStandards'
        subtitle?: string
        heading?: string
        description?: string
        features?: Array<{
          title?: string
          description?: string
          icon?: 'clipboard' | 'refresh' | 'shield'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'services'
        heading?: string
        subheading?: string
        description?: string
        serviceItems?: Array<{
          title?: string
          description?: string
          icon?: 'Factory' | 'PenTool' | 'ShieldCheck' | 'Truck'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'stats'
        items?: Array<{
          value?: string
          label?: string
          icon?: 'Award' | 'Factory' | 'Globe' | 'Leaf' | 'ShieldCheck' | 'Users'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'workflowSection'
        subtitle?: string
        heading?: string
        description?: string
        steps?: Array<{
          number?: string
          title?: string
          description?: string
          _key: string
        }>
      }
  > | null
} | null

// Source: sanity\lib\queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'post'
      _updatedAt: string
    }
>

// Source: sanity\lib\queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity\lib\queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity\lib\queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page: string | null
          post: string | null
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
} | null

// Source: sanity\lib\queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity\lib\queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity\lib\queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    headerMenu,    footerDescription,    contactEmail,    locations,    socialLinks,    "profileUrl": companyProfile.asset->url,    copyrightText,    legalLinks,    certificationsText   }
export type SETTINGS_QUERY_RESULT = {
  headerMenu: Array<{
    title?: string
    link?: string
    _key: string
  }> | null
  footerDescription: string | null
  contactEmail: string | null
  locations: Array<{
    city?: string
    address?: string
    _key: string
  }> | null
  socialLinks: Array<{
    platform?: string
    url?: string
    _key: string
  }> | null
  profileUrl: string | null
  copyrightText: string | null
  legalLinks: Array<{
    label?: string
    url?: string
    _key: string
  }> | null
  certificationsText: string | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n  }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n      _type == "productLookbook" => {\n        ...,\n        products[]->{\n          _id,\n          title,\n          description,\n          image,\n          features\n        }\n      },\n      // \uD83D\uDC47 ADD YOUR NEW BLOCKS HERE IF NEEDED TO FETCH DATA\n      _type == "brandShowcase" => { ... },\n      _type == "contactSection" => { ... },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "siteSettings"][0] {\n    headerMenu,\n    footerDescription,\n    contactEmail,\n    locations,\n    socialLinks,\n    "profileUrl": companyProfile.asset->url,\n    copyrightText,\n    legalLinks,\n    certificationsText \n  }\n': SETTINGS_QUERY_RESULT
  }
}
