/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ..\sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Logo = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type LocationsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type GalleryItemImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "galleryItem.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ProductsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "products.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type ResourceItemFile = {
  asset?: SanityFileAssetReference
  media?: unknown // Unable to locate the referenced type "file.media" in schema
  _type: 'file'
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  openGraphImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Location = {
  _id: string
  _type: 'location'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  type?: 'source' | 'target'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  coordinates?: Geopoint
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  legalType?: 'privacy' | 'terms'
  seo?: Seo
  pageBuilder?: Array<
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & Stats)
    | ({
        _key: string
      } & BrandShowcase)
    | ({
        _key: string
      } & Philosophy)
    | ({
        _key: string
      } & Services)
    | ({
        _key: string
      } & CtaSection)
    | ({
        _key: string
      } & ProductLookbook)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & AboutHero)
    | ({
        _key: string
      } & LocationSection)
    | ({
        _key: string
      } & GallerySection)
    | ({
        _key: string
      } & WorkflowSection)
    | ({
        _key: string
      } & InfrastructureSection)
    | ({
        _key: string
      } & ProductShowcase)
    | ({
        _key: string
      } & QualityStandards)
    | ({
        _key: string
      } & QualityEthics)
    | ({
        _key: string
      } & ContactSection)
    | ({
        _key: string
      } & RichTextSection)
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & ResourceSection)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type ResourceSection = {
  _type: 'resourceSection'
  eyebrow?: string
  heading: string
  description?: string
  formTitle?: string
  formDescription?: string
  formButtonText?: string
  successTitle?: string
  successMessage?: string
  resources?: Array<{
    title: string
    description?: string
    file: ResourceItemFile
    type?: 'PDF' | 'PPT' | 'XLS'
    isGated?: boolean
    _type: 'resourceItem'
    _key: string
  }>
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  logo?: {
    useCustomUrl?: boolean
    logoImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    logoUrl?: string
    logoMobileImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    logoMobileUrl?: string
    alt?: string
  }
  headerMenu?: Array<{
    title?: string
    link?: string
    _key: string
  }>
  footerDescription?: string
  contactEmail?: string
  locations?: Array<{
    city?: string
    address?: string
    _key: string
  }>
  socialLinks?: Array<{
    platform?: string
    url?: string
    _key: string
  }>
  companyProfile?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  copyrightText?: string
  legalLinks?: Array<{
    label?: string
    url?: string
    _key: string
  }>
  certificationsText?: string
}

export type ContactSection = {
  _type: 'contactSection'
  subtitle: string
  heading: string
  description?: string
  addressHeading?: string
  address?: string
  mapEmbedUrl?: string
  googleMapsLink?: string
  mapImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  phoneHeading?: string
  phones?: Array<string>
  emailHeading?: string
  email?: string
  hoursHeading?: string
  hours?: string
  productCategories?: Array<string>
}

export type QualityEthics = {
  _type: 'qualityEthics'
  layout?: 'left' | 'right'
  subtitle?: string
  heading: string
  description?: string
  checklist?: Array<string>
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type QualityStandards = {
  _type: 'qualityStandards'
  subtitle: string
  heading: string
  description?: string
  features?: Array<{
    title: string
    description?: string
    icon?: 'shield' | 'refresh' | 'clipboard' | 'scale' | 'zap'
    _key: string
  }>
}

export type ProductShowcase = {
  _type: 'productShowcase'
  subtitle: string
  heading: string
  description?: string
  products?: Array<{
    number: string
    title: string
    description: string
    moq?: string
    leadTime?: string
    features?: Array<string>
    image: ProductsObjectImage
    buttonText?: string
    buttonLink?: string
    _key: string
  }>
}

export type ProductCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'productCategory'
}

export type ProductLookbook = {
  _type: 'productLookbook'
  heading?: string
  products?: Array<
    {
      _key: string
    } & ProductCategoryReference
  >
}

export type ProductCategory = {
  _id: string
  _type: 'productCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  features?: Array<string>
}

export type InfrastructureSection = {
  _type: 'infrastructureSection'
  subtitle?: string
  heading?: string
  description?: string
  cards?: Array<{
    icon?: 'design' | 'precision' | 'testing'
    title?: string
    description?: string
    _key: string
  }>
}

export type Services = {
  _type: 'services'
  heading?: string
  subheading?: string
  description?: string
  serviceItems?: Array<{
    title?: string
    description?: string
    icon?: 'PenTool' | 'Factory' | 'ShieldCheck' | 'Truck'
    _key: string
  }>
}

export type WorkflowSection = {
  _type: 'workflowSection'
  subtitle: string
  heading: string
  description?: string
  steps?: Array<{
    number: string
    title: string
    description?: string
    _key: string
  }>
}

export type GallerySection = {
  _type: 'gallerySection'
  subtitle: string
  heading: string
  items?: Array<{
    image: GalleryItemImage
    title?: string
    description?: string
    link?: string
    _type: 'galleryItem'
    _key: string
  }>
}

export type LocationSection = {
  _type: 'locationSection'
  locations?: Array<{
    label: string
    city: string
    description?: string
    image?: LocationsObjectImage
    features?: Array<string>
    _key: string
  }>
}

export type RichTextSection = {
  _type: 'richTextSection'
  containerWidth?: 'max-w-3xl' | 'max-w-6xl' | 'max-w-full'
  title?: string
  lastUpdated?: string
  introduction?: string
  legalSections?: Array<{
    heading?: string
    content?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _key: string
  }>
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Table)
  >
}

export type AboutHero = {
  _type: 'aboutHero'
  layout?: 'left' | 'right'
  subtitle: string
  heading: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<
      | {
          value?: string
          _type: 'textColor'
          _key: string
        }
      | {
          size?:
            | 'text-5xl md:text-7xl lg:text-[5rem] leading-[0.9]'
            | 'text-4xl md:text-5xl lg:text-6xl leading-[1]'
            | 'text-3xl md:text-4xl lg:text-5xl leading-[1.1]'
            | 'text-2xl md:text-3xl lg:text-3xl'
          _type: 'textSize'
          _key: string
        }
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  description?: string
  quote?: string
  quoteAuthor?: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  statNumber?: string
  statLabel?: string
}

export type CtaSection = {
  _type: 'ctaSection'
  subtitle: string
  heading: string
  description?: string
  primaryButtonText?: string
  primaryButtonLink?: string
  secondaryButtonText?: string
  secondaryButtonLink?: string
}

export type Philosophy = {
  _type: 'philosophy'
  heading?: string
  subheading?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  features?: Array<string>
  ctaText?: string
  ctaLink?: string
}

export type BrandShowcase = {
  _type: 'brandShowcase'
  subtitle: string
  heading: string
  description?: string
  brands?: Array<{
    name: string
    logo: Logo
    image: ObjectImage
    description?: string
    website?: string
    color?: string
    _key: string
  }>
}

export type Stats = {
  _type: 'stats'
  items?: Array<{
    value?: string
    label?: string
    icon?: 'Globe' | 'Award' | 'Factory' | 'Users' | 'Leaf' | 'ShieldCheck'
    _key: string
  }>
}

export type Hero = {
  _type: 'hero'
  heading: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<
      | {
          value?: string
          _type: 'textColor'
          _key: string
        }
      | {
          size?:
            | 'text-5xl sm:text-7xl md:text-8xl lg:text-8xl xl:text-[9rem] leading-[0.9]'
            | 'text-4xl sm:text-6xl md:text-7xl lg:text-[7rem] leading-[0.9]'
            | 'text-3xl sm:text-5xl md:text-6xl lg:text-[5rem] leading-[1]'
            | 'text-2xl sm:text-4xl md:text-5xl lg:text-5xl leading-[1.1]'
            | 'text-xl sm:text-2xl md:text-3xl lg:text-4xl'
          _type: 'textSize'
          _key: string
        }
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  subheading?: string
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  buttonText?: string
  buttonLink?: string
  secondaryButtonText?: string
  secondaryButtonLink?: string
}

export type Table = {
  _type: 'table'
  rows?: Array<
    {
      _key: string
    } & TableRow
  >
}

export type TableRow = {
  _type: 'tableRow'
  cells?: Array<string>
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Logo
  | ObjectImage
  | LocationsObjectImage
  | GalleryItemImage
  | ProductsObjectImage
  | SanityFileAssetReference
  | ResourceItemFile
  | Seo
  | Location
  | Geopoint
  | SanityImageCrop
  | SanityImageHotspot
  | InfoSection
  | PageReference
  | PostReference
  | Link
  | CallToAction
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Page
  | PersonReference
  | Post
  | Person
  | Slug
  | ResourceSection
  | SiteSettings
  | ContactSection
  | QualityEthics
  | QualityStandards
  | ProductShowcase
  | ProductCategoryReference
  | ProductLookbook
  | ProductCategory
  | InfrastructureSection
  | Services
  | WorkflowSection
  | GallerySection
  | LocationSection
  | RichTextSection
  | AboutHero
  | CtaSection
  | Philosophy
  | BrandShowcase
  | Stats
  | Hero
  | Table
  | TableRow
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset

export declare const internalGroqTypeReferenceTo: unique symbol
